### ISSUE TITLE
Can't start JasperService

### ISSUE THREAD

**Issue by squarepegsys** [yakworks/grails-jasper-reports#7]
Using Grails 3.3.4 and I put in the plugin dependency: 

    compile 'org.grails.plugins:jasper-reports:3.1.1'

And on startup I got: 
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class nine.jasper.JasperService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 23 common frames omitted
Caused by: org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class nine.jasper.JasperService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetException
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:170)
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:825)
        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:815)
        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:800)
        at org.grails.plugins.AbstractGrailsPluginManager.registerProvidedArtefacts(AbstractGrailsPluginManager.java:310)
[snip]
Caused by: java.lang.NullPointerException: null
        at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1337)
        at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
        at java.beans.Introspector.getBeanInfo(Introspector.java:426)
        at java.beans.Introspector.getBeanInfo(Introspector.java:173)
        at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3328)
        at java.security.AccessController.doPrivileged(Native Method)
        at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3326)

I'm ok downgrading the Grails version, I would just like to know what you have tested it with.

**Comment by basejump** [comment]
works on 3.3.9
